
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN CLASS DIVIDE DOT IDENTIFIER LBRACE LBRACKET LPAREN MAIN OUT PRINTLN PUBLIC RBRACE RBRACKET RPAREN SEMI STATIC STRING STRING_TYPE SYSTEM TIMES VOIDprogram : class_declarationclass_declaration : PUBLIC CLASS IDENTIFIER LBRACE method_declarations RBRACEmethod_declarations : method_declaration\n                               | method_declarations method_declarationmethod_declaration : PUBLIC STATIC VOID MAIN LPAREN STRING_TYPE LBRACKET RBRACKET IDENTIFIER RPAREN LBRACE statement RBRACEstatement : SYSTEM DOT OUT DOT PRINTLN LPAREN STRING RPAREN SEMI'
    
_lr_action_items = {'PUBLIC':([0,6,8,9,12,24,],[3,7,7,-3,-4,-5,]),'$end':([1,2,11,],[0,-1,-2,]),'CLASS':([3,],[4,]),'IDENTIFIER':([4,18,],[5,19,]),'LBRACE':([5,20,],[6,21,]),'STATIC':([7,],[10,]),'RBRACE':([8,9,12,22,24,32,],[11,-3,-4,24,-5,-6,]),'VOID':([10,],[13,]),'MAIN':([13,],[14,]),'LPAREN':([14,28,],[15,29,]),'STRING_TYPE':([15,],[16,]),'LBRACKET':([16,],[17,]),'RBRACKET':([17,],[18,]),'RPAREN':([19,30,],[20,31,]),'SYSTEM':([21,],[23,]),'DOT':([23,26,],[25,27,]),'OUT':([25,],[26,]),'PRINTLN':([27,],[28,]),'STRING':([29,],[30,]),'SEMI':([31,],[32,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'class_declaration':([0,],[2,]),'method_declarations':([6,],[8,]),'method_declaration':([6,8,],[9,12,]),'statement':([21,],[22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> class_declaration','program',1,'p_program','app.py',65),
  ('class_declaration -> PUBLIC CLASS IDENTIFIER LBRACE method_declarations RBRACE','class_declaration',6,'p_class_declaration','app.py',69),
  ('method_declarations -> method_declaration','method_declarations',1,'p_method_declarations','app.py',73),
  ('method_declarations -> method_declarations method_declaration','method_declarations',2,'p_method_declarations','app.py',74),
  ('method_declaration -> PUBLIC STATIC VOID MAIN LPAREN STRING_TYPE LBRACKET RBRACKET IDENTIFIER RPAREN LBRACE statement RBRACE','method_declaration',13,'p_method_declaration','app.py',78),
  ('statement -> SYSTEM DOT OUT DOT PRINTLN LPAREN STRING RPAREN SEMI','statement',9,'p_statement','app.py',82),
]
